version: 2
updates:
    - package-ecosystem: 'npm'
      directory: '/'
      reviewers:
       - "bartdelange"
      schedule:
          interval: 'weekly'
      groups:
          production-version-updates:
              applies-to: version-updates
              dependency-type: "development"
              update-types:
                  - 'minor'
                  - 'patch'
          development-version-updates:
              applies-to: version-updates
              dependency-type: "development"
              update-types:
                  - 'minor'
                  - 'patch'
          security-updates:
              applies-to: security-updates
              update-types:
                  - 'minor'
                  - 'patch'
      commit-message:
          prefix: 'chore(NPM Dependency Updates): '
      labels:
          - 'npm'
          - 'dependencies'
