name: Deploy to Testflight
on:
  release:
    types: [created]

jobs:
  deploy:
    name: Deploy
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Select Xcode version
        run: sudo xcode-select -s '/Applications/Xcode_12.4.app/Contents/Developer'

      - name: Bundle install
        run: cd ./ios && bundle install

      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: "12.x"

      - name: Setup Keys for fastlane and fastlane match
        run: |
          echo "$FASTLANE_KEY" > ./ios/authkey.p8
          SSH_PATH="$HOME/.ssh"
          mkdir -p "$SSH_PATH"
          touch "$SSH_PATH/known_hosts"
          echo "$PRIVATE_KEY" > "$SSH_PATH/id_rsa"
          chmod 700 "$SSH_PATH"
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          chmod 600 "$SSH_PATH/known_hosts"
          chmod 600 "$SSH_PATH/id_rsa"
          eval $(ssh-agent)
          ssh-add "$SSH_PATH/id_rsa"
        env:
          PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          FASTLANE_KEY: ${{ secrets.FASTLANE_KEY }}

      - name: Setup flutter
        uses: subosito/flutter-action@v1
        with:
          flutter-version: "2.5.1"
          channel: "stable"

      - name: Install tools
        run: |
          flutter pub get
          cd ./ios && pod install

      - name: Deploy to TestFlight
        run: |
          cd ./ios
          bundle exec fastlane set_release_version
          bundle exec fastlane beta
        env:
          TEAM_ID: ${{ secrets.TEAM_ID }}
          ITC_TEAM_ID: ${{ secrets.ITC_TEAM_ID }}
          FASTLANE_KEY_ID: ${{ secrets.FASTLANE_KEY_ID }}
          FASTLANE_ISSUER_ID: ${{ secrets.FASTLANE_ISSUER_ID }}
          MATCH_PASSWORD: ${{ secrets.MATCH_PASSWORD }}
          MATCH_KEYCHAIN_NAME: ${{ secrets.MATCH_KEYCHAIN_NAME }}
          MATCH_KEYCHAIN_PASSWORD: ${{ secrets.MATCH_KEYCHAIN_PASSWORD }}
          DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS: ${{ secrets.DELIVER_ITMSTRANSPORTER_ADDITIONAL_UPLOAD_PARAMETERS }}
          RELEASE_VERSION: ${{ github.event.release.tag_name }}
          CHANGELOG: ${{ github.event.release.body }}