name: PR checks
on:
  pull_request:
    branches-ignore: "dependabot/**"
jobs:
  install-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install npm dependencies
        run: npm ci

      - name: Run tests
        run: npm test

  build-android:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install npm dependencies
        run: npm ci

      - name: Build Android apk (debug)
        run: ./gradlew assembleDebug -Dorg.gradle.logging.level=info
        working-directory: android


  build-ios:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install npm dependencies
        run: npm ci

      - name: Setup XCode
        run: xcode-select -p

      - name: Install pod dependencies
        working-directory: ios
        run: pod install

      - name: Build iOS (debug)
        run: xcodebuild -workspace throwl.xcworkspace -scheme throwl clean archive -sdk iphoneos -configuration Debug -UseModernBuildSystem=NO -archivePath $PWD/throwl CODE_SIGNING_ALLOWED=NO


