name: Build and deploy

on:
  workflow_call:
    inputs:
      os:
        type: string
        required: true
      store:
        type: string
        required: true
      working_directory:
        type: string
        required: true
        description: One of `ios` or `android`

    secrets:
      # iOS
      APP_STORE_CONNECT_TEAM_ID:
        required: true
      DEVELOPER_APP_ID:
        required: true
      DEVELOPER_APP_IDENTIFIER:
        required: true
      DEVELOPER_PORTAL_TEAM_ID:
        required: true
      FASTLANE_APPLE_ID:
        required: true
      MATCH_PASSWORD:
        required: true
      MATCH_GIT_BASIC_AUTHORIZATION:
        required: true
      APPLE_KEY_ID:
        required: true
      APPLE_ISSUER_ID:
        required: true
      APPLE_KEY_CONTENT:
        required: true

      # Android
      ANDROID_KEYSTORE_FILE:
        required: true
      KEYSTORE_KEY_ALIAS:
        required: true
      KEYSTORE_KEY_PASSWORD:
        required: true
      KEYSTORE_STORE_PASSWORD:
        required: true
      PLAY_CONFIG_JSON:
        required: true

jobs:
  build_and_deploy:
    name: Build and deploy to ${{ inputs.store }},
    runs-on: ${{ inputs.os }}
    permissions:
      contents: read
    concurrency:
      group: ${{ github.workflow }}-${{ inputs.os }}
      cancel-in-progress: true
    steps:
      - name: Setup directory and install required packages
        uses: ./.github/actions/reusable-setup/
        with:
          os: ubuntu-latest
          working_directory: ${{ inputs.working_directory }}
          bundle: true
      #region Android
      - name: Use JAVA 22
        if: ${{ inputs.working_directory == 'android' }}
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '22.0.2'

      - name: Configure Keystore
        if: ${{ inputs.working_directory == 'android' }}
        working-directory: ${{ inputs.working_directory }}
        run: |
          echo "$ANDROID_KEYSTORE_FILE" > keystore.jks.b64
          base64 -d -i keystore.jks.b64 > app/keystore.jks
          echo "storeFile=keystore.jks" >> keystore.properties
          echo "keyAlias=$KEYSTORE_KEY_ALIAS" >> keystore.properties
          echo "storePassword=$KEYSTORE_STORE_PASSWORD" >> keystore.properties
          echo "keyPassword=$KEYSTORE_KEY_PASSWORD" >> keystore.properties
        env:
          ANDROID_KEYSTORE_FILE: ${{ secrets.ANDROID_KEYSTORE_FILE }}
          KEYSTORE_KEY_ALIAS: ${{ secrets.ANDROID_KEYSTORE_ALIAS }}
          KEYSTORE_KEY_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
          KEYSTORE_STORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}

      - name: Create Google Play Config file
        if: ${{ inputs.working_directory == 'android' }}
        working-directory: ${{ inputs.working_directory }}
        run: |
          echo "$PLAY_CONFIG_JSON" > playstore_config.json.b64
          base64 -d -i playstore_config.json.b64 > playstore_config.json
        env:
          PLAY_CONFIG_JSON: ${{ env.PLAY_CONFIG_JSON }}
      #endregion

      #region iOS
      - name: Use latest xcode
        if: ${{ inputs.working_directory == 'ios' }}
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: 15.4.0
      #endregion

      - name: Distribute app to ${{ inputs.store }} ðŸš€
        working-directory: ${{ inputs.working_directory }}
        run: bundle exec fastlane beta
        env:
          APP_STORE_CONNECT_TEAM_ID: ${{ (inputs.working_directory == 'ios' && secrets.APP_STORE_CONNECT_TEAM_ID) || '' }}
          DEVELOPER_APP_ID: ${{ (inputs.working_directory == 'ios' && secrets.DEVELOPER_APP_ID) || '' }}
          DEVELOPER_APP_IDENTIFIER: ${{ (inputs.working_directory == 'ios' && secrets.DEVELOPER_APP_IDENTIFIER) || '' }}
          DEVELOPER_PORTAL_TEAM_ID: ${{ (inputs.working_directory == 'ios' && secrets.DEVELOPER_PORTAL_TEAM_ID) || '' }}
          FASTLANE_APPLE_ID: ${{ (inputs.working_directory == 'ios' && secrets.FASTLANE_APPLE_ID) || '' }}
          MATCH_PASSWORD: ${{ (inputs.working_directory == 'ios' && secrets.MATCH_PASSWORD) || '' }}
          MATCH_GIT_BASIC_AUTHORIZATION: ${{ (inputs.working_directory == 'ios' && secrets.MATCH_GIT_BASIC_AUTHORIZATION) || '' }}
          APPLE_KEY_ID: ${{ (inputs.working_directory == 'ios' && secrets.APPLE_KEY_ID) || '' }}
          APPLE_ISSUER_ID: ${{ (inputs.working_directory == 'ios' && secrets.APPLE_ISSUER_ID) || '' }}
          APPLE_KEY_CONTENT: ${{ (inputs.working_directory == 'ios' && secrets.APPLE_KEY_CONTENT) || '' }}
