name: Build and deploy

on:
  workflow_call:
    inputs:
      os:
        type: string
        required: true
      store:
        type: string
        required: true
      working_directory:
        type: string
        required: true
        description: One of `ios` or `android`

    secrets:
      # iOS
      IOS_APP_STORE_CONNECT_TEAM_ID:
      IOS_DEVELOPER_APP_ID:
      IOS_DEVELOPER_APP_IDENTIFIER:
      IOS_DEVELOPER_PORTAL_TEAM_ID:
      IOS_FASTLANE_APPLE_ID:
      IOS_MATCH_PASSWORD:
      IOS_MATCH_GIT_BASIC_AUTHORIZATION:
      IOS_APPLE_KEY_ID:
      IOS_APPLE_ISSUER_ID:
      IOS_APPLE_KEY_CONTENT:

      # Android
      ANDROID_KEYSTORE_FILE:
      ANDROID_KEYSTORE_KEY_ALIAS:
      ANDROID_KEYSTORE_KEY_PASSWORD:
      ANDROID_KEYSTORE_STORE_PASSWORD:
      ANDROID_PLAY_CONFIG_JSON:

jobs:
  build_and_deploy:
    name: Build and Deploy to ${{ inputs.store }},
    runs-on: ${{ inputs.os }}
    permissions:
      contents: read
    concurrency:
      group: ${{ github.workflow }}-${{ inputs.os }}
      cancel-in-progress: true
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup directory and install required packages
        uses: ./.github/actions/reusable-setup/
        with:
          os: ubuntu-latest
          working_directory: ${{ inputs.working_directory }}
          bundle: true
      #region Android
      - name: Use JAVA 22
        if: ${{ inputs.working_directory == 'android' }}
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu' # See 'Supported distributions' for available options
          java-version: '22.0.2'

      - name: Configure Keystore
        if: ${{ inputs.working_directory == 'android' }}
        working-directory: ${{ inputs.working_directory }}
        run: |
          echo "$KEYSTORE_FILE" > keystore.jks.b64
          base64 -d -i keystore.jks.b64 > app/keystore.jks
          echo "storeFile=keystore.jks" >> keystore.properties
          echo "keyAlias=$KEYSTORE_KEY_ALIAS" >> keystore.properties
          echo "storePassword=$KEYSTORE_STORE_PASSWORD" >> keystore.properties
          echo "keyPassword=$KEYSTORE_KEY_PASSWORD" >> keystore.properties
        env:
          KEYSTORE_FILE: ${{ secrets.ANDROID_KEYSTORE_FILE }}
          KEYSTORE_KEY_ALIAS: ${{ secrets.ANDROID_KEYSTORE_KEY_ALIAS }}
          KEYSTORE_KEY_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_KEY_PASSWORD }}
          KEYSTORE_STORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_STORE_PASSWORD }}

      - name: Create Google Play Config file
        if: ${{ inputs.working_directory == 'android' }}
        working-directory: ${{ inputs.working_directory }}
        run: |
          echo "$PLAY_CONFIG_JSON" > playstore_config.json.b64
          base64 -d -i playstore_config.json.b64 > playstore_config.json
        env:
          PLAY_CONFIG_JSON: ${{ secrets.ANDROID_PLAY_CONFIG_JSON }}
      #endregion

      #region iOS
      - name: Use latest xcode
        if: ${{ inputs.working_directory == 'ios' }}
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest-stable
      #endregion

      - name: Distribute app to ${{ inputs.store }} ðŸš€
        working-directory: ${{ inputs.working_directory }}
        run: bundle exec fastlane beta
        env:
          APP_STORE_CONNECT_TEAM_ID: ${{ (inputs.working_directory == 'ios' && secrets.IOS_APP_STORE_CONNECT_TEAM_ID) || '' }}
          DEVELOPER_APP_ID: ${{ (inputs.working_directory == 'ios' && secrets.IOS_DEVELOPER_APP_ID) || '' }}
          DEVELOPER_APP_IDENTIFIER: ${{ (inputs.working_directory == 'ios' && secrets.IOS_DEVELOPER_APP_IDENTIFIER) || '' }}
          DEVELOPER_PORTAL_TEAM_ID: ${{ (inputs.working_directory == 'ios' && secrets.IOS_DEVELOPER_PORTAL_TEAM_ID) || '' }}
          FASTLANE_APPLE_ID: ${{ (inputs.working_directory == 'ios' && secrets.IOS_FASTLANE_APPLE_ID) || '' }}
          MATCH_PASSWORD: ${{ (inputs.working_directory == 'ios' && secrets.IOS_MATCH_PASSWORD) || '' }}
          MATCH_GIT_BASIC_AUTHORIZATION: ${{ (inputs.working_directory == 'ios' && secrets.IOS_MATCH_GIT_BASIC_AUTHORIZATION) || '' }}
          APPLE_KEY_ID: ${{ (inputs.working_directory == 'ios' && secrets.IOS_APPLE_KEY_ID) || '' }}
          APPLE_ISSUER_ID: ${{ (inputs.working_directory == 'ios' && secrets.IOS_APPLE_ISSUER_ID) || '' }}
          APPLE_KEY_CONTENT: ${{ (inputs.working_directory == 'ios' && secrets.IOS_APPLE_KEY_CONTENT) || '' }}
